version: '3.1'
services:
  postgres-camunda:
    image: library/postgres:12
    environment:
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: admin1password
      POSTGRES_DB: primary
    ports:
      - "5432:5432"

  postgres-poc:
    image: library/postgres:12
    environment:
      POSTGRES_USER: admin2
      POSTGRES_PASSWORD: admin2password
      POSTGRES_DB: secondary
    ports:
      - "5433:5432"
